version: '3.9'

services:
 django:
    build: .
    container_name: photoapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/photoapp
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1